window.TRAUMAKORP_BOOKS = [
  {id:1,title:"Swan Song",author:"Charles Spencer",category:"New Releases",price:24.50,format:"Hardcover"},
  {id:2,title:"Murder at the Grand Alpine Hotel",author:"Lucy Foley, Agatha Christie",category:"New Releases",price:27.00,format:"Hardcover"},
  {id:3,title:"Rock*: A Mainstream Alternative History of Alternative Mainstream Music",author:"Chuck Klosterman",category:"New Releases",price:29.50,format:"Hardcover"},
  {id:4,title:"An Unexpected Life: A Memoir",author:"Gloria Steinem",category:"New Releases",price:27.00,format:"Hardcover"},
  {id:5,title:"Hollow Bones: A Novel",author:"Jodi Picoult",category:"New Releases",price:23.80,format:"Hardcover"},
  {id:6,title:"The Art of Gravity Falls",author:"Alex Hirsch, Rob Renzetti",category:"New Releases",price:55.00,format:"B&N Exclusive"},
  {id:7,title:"Scion",author:"James Islington",category:"New Releases",price:25.00,format:"B&N Exclusive"},
  {id:8,title:"The Mirror of Infinite Endings",author:"Stephanie Garber",category:"New Releases",price:21.99,format:"B&N Exclusive"},

  {id:9,title:"The Everlasting",author:"Alix E. Harrow",category:"Fantasy & Sci-Fi",price:26.99,format:"Hardcover"},
  {id:10,title:"The River Has Roots",author:"Amal El-Mohtar",category:"Fantasy & Sci-Fi",price:17.99,format:"Paperback"},
  {id:11,title:"The Shattering Peace",author:"John Scalzi",category:"Fantasy & Sci-Fi",price:18.99,format:"Paperback"},
  {id:12,title:"A Wizard of Earthsea: A Graphic Novel",author:"Ursula K. Le Guin",category:"Fantasy & Sci-Fi",price:26.99,format:"Hardcover"},
  {id:13,title:"Coffeeshop in an Alternate Universe",author:"C. B. Lee",category:"Fantasy & Sci-Fi",price:14.99,format:"Paperback"},
  {id:14,title:"The Raven Scholar",author:"Antonia Hodgson",category:"Fantasy & Sci-Fi",price:21.99,format:"Paperback"},
  {id:15,title:"Project Hail Mary",author:"Andy Weir",category:"Fantasy & Sci-Fi",price:22.00,format:"Paperback"},
  {id:16,title:"Dune: Deluxe Trade Paperback Edition",author:"Frank Herbert",category:"Fantasy & Sci-Fi",price:22.00,format:"Paperback"},

  {id:17,title:"The Love Hypothesis",author:"Ali Hazelwood",category:"Romance",price:16.00,format:"Paperback"},
  {id:18,title:"The Love Hypothesis (Prime Tie-In)",author:"Ali Hazelwood",category:"Romance",price:17.00,format:"Paperback"},
  {id:19,title:"The Love Hypothesis (Collector's Edition)",author:"Ali Hazelwood",category:"Romance",price:35.00,format:"Special Edition"},
  {id:20,title:"Grim Tidings: A Novel",author:"B.K. Borison",category:"Romance",price:16.99,format:"Paperback"},
  {id:21,title:"Verity",author:"Colleen Hoover",category:"Romance",price:15.99,format:"Paperback"},
  {id:22,title:"Shield of Sparrows",author:"Devney Perry",category:"Romance",price:16.99,format:"Paperback"},
  {id:23,title:"A Court of Thorns and Roses",author:"Sarah J. Maas",category:"Romance",price:19.00,format:"Paperback"},
  {id:24,title:"The Deal",author:"Elle Kennedy",category:"Romance",price:16.99,format:"Paperback"},

  {id:25,title:"The Dying Light: A Detective Matthew Venn Novel",author:"Ann Cleeves",category:"Mystery & Thrillers",price:14.50,format:"Hardcover"},
  {id:26,title:"All In",author:"David Baldacci",category:"Mystery & Thrillers",price:16.00,format:"Hardcover"},
  {id:27,title:"Robert B. Parker's Framed",author:"Mike Lupica",category:"Mystery & Thrillers",price:15.00,format:"Hardcover"},
  {id:28,title:"Bleed",author:"Robin Cook",category:"Mystery & Thrillers",price:16.00,format:"Hardcover"},
  {id:29,title:"The Family Cross: An Alex Cross Thriller",author:"James Patterson",category:"Mystery & Thrillers",price:16.00,format:"Hardcover"},
  {id:30,title:"The Hollow: A Harry Bosch Novel",author:"Michael Connelly",category:"Mystery & Thrillers",price:16.00,format:"Hardcover"},
  {id:31,title:"Death on the Lanai",author:"Rachel Ekstrom Courage",category:"Mystery & Thrillers",price:15.99,format:"Paperback"},
  {id:32,title:"Sheepdogs: A Novel",author:"Elliot Ackerman",category:"Mystery & Thrillers",price:15.00,format:"Paperback"},

  {id:33,title:"Frankenstein",author:"Mary Shelley",category:"Horror",price:9.99,format:"Paperback"},
  {id:34,title:"Dracula",author:"Bram Stoker",category:"Horror",price:9.99,format:"Paperback"},
  {id:35,title:"The Haunting of Hill House",author:"Shirley Jackson",category:"Horror",price:18.00,format:"Paperback"},
  {id:36,title:"The Exorcist: A Novel",author:"William Peter Blatty",category:"Horror",price:12.00,format:"Paperback"},
  {id:37,title:"The Shining",author:"Stephen King",category:"Horror",price:17.00,format:"Paperback"},
  {id:38,title:"Ring",author:"Koji Suzuki",category:"Horror",price:16.95,format:"B&N Exclusive"},
  {id:39,title:"The Only Good Indians",author:"Stephen Graham Jones",category:"Horror",price:19.00,format:"Paperback"},
  {id:40,title:"Tender Is the Flesh",author:"Agustina Bazterrica",category:"Horror",price:17.99,format:"Paperback"},

  {id:41,title:"The Great Gatsby",author:"F. Scott Fitzgerald",category:"Classics & Literary",price:17.00,format:"Paperback"},
  {id:42,title:"To Kill a Mockingbird",author:"Harper Lee",category:"Classics & Literary",price:16.99,format:"Paperback"},
  {id:43,title:"Horse",author:"Geraldine Brooks",category:"Classics & Literary",price:19.00,format:"Paperback"},
  {id:44,title:"Brooklyn",author:"Colm Tóibín",category:"Classics & Literary",price:18.00,format:"Paperback"},
  {id:45,title:"Lincoln in the Bardo",author:"George Saunders",category:"Classics & Literary",price:21.00,format:"Paperback"},
  {id:46,title:"Their Eyes Were Watching God",author:"Zora Neale Hurston",category:"Classics & Literary",price:17.99,format:"Paperback"},
  {id:47,title:"The Bell Jar",author:"Sylvia Plath",category:"Classics & Literary",price:18.99,format:"Paperback"},
  {id:48,title:"Pride and Prejudice",author:"Jane Austen",category:"Classics & Literary",price:12.99,format:"Paperback"},

  {id:49,title:"The Pumpkin Thief",author:"Alice Hemming",category:"Kids",price:18.99,format:"Hardcover"},
  {id:50,title:"A Book for Everyone",author:"Hayley Rocco",category:"Kids",price:18.99,format:"Hardcover"},
  {id:51,title:"Pete the Cat and the Cookie Catastrophe",author:"James Dean, Kimberly Dean",category:"Kids",price:19.99,format:"Hardcover"},
  {id:52,title:"Beware the Sock Monkeys!",author:"Jonathan Stutzman",category:"Kids",price:18.99,format:"Hardcover"},
  {id:53,title:"Horizontal Crocodile",author:"Scott Rothman",category:"Kids",price:19.99,format:"Hardcover"},
  {id:54,title:"Gruffalo Granny",author:"Julia Donaldson",category:"Kids",price:17.99,format:"Hardcover"},
  {id:55,title:"The Very Hungry Caterpillar",author:"Eric Carle",category:"Kids",price:10.99,format:"Board Book"},
  {id:56,title:"The Little Prince",author:"Antoine de Saint-Exupéry",category:"Kids",price:12.99,format:"Paperback"},

  {id:57,title:"The Let Them Theory",author:"Mel Robbins, Sawyer Robbins",category:"Growth & Business",price:24.99,format:"Hardcover"},
  {id:58,title:"Atomic Habits",author:"James Clear",category:"Growth & Business",price:22.00,format:"Hardcover"},
  {id:59,title:"The Psychology of Money",author:"Morgan Housel",category:"Growth & Business",price:19.99,format:"Paperback"},
  {id:60,title:"Better Every Day: An Action Plan for a Full Life",author:"Arnold Schwarzenegger",category:"Growth & Business",price:28.00,format:"Hardcover"},
  {id:61,title:"Poems & Prayers",author:"Matthew McConaughey",category:"Growth & Business",price:26.00,format:"Hardcover"},
  {id:62,title:"1929: Inside the Greatest Crash in Wall Street History",author:"Andrew Ross Sorkin",category:"Growth & Business",price:32.00,format:"Hardcover"},
  {id:63,title:"Rich Dad Poor Dad",author:"Robert T. Kiyosaki",category:"Growth & Business",price:8.99,format:"eBook"},
  {id:64,title:"Unreasonable Hospitality",author:"Will Guidara",category:"Growth & Business",price:13.99,format:"eBook"}
];
